name: Build and Release Debian Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Déclenche la release sur push de tags commençant par v

permissions:
  contents: write

env:
  PYSERV_VERSION: 1.0.0  # Mets à jour cette version manuellement ou via tag

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev devscripts debhelper dh-python python3-all

      - name: Make postinst executable
        run: |
          chmod +x pyserv/DEBIAN/postinst

      - name: Build Debian package
        run: |
          mkdir -p build/pyserv
          cp -R pyserv/DEBIAN build/pyserv/
          cp -R pyserv/usr build/pyserv/
          cd build
          dpkg-deb --build pyserv

      - name: Rename package with version
        run: |
          cd build
          mv pyserv.deb pyserv-v${{ env.PYSERV_VERSION }}.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyserv-deb
          path: build/pyserv-v${{ env.PYSERV_VERSION }}.deb

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: build/pyserv-v${{ env.PYSERV_VERSION }}.deb
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
