name: Build and Release Debian Package

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  PYSERV_VERSION: 1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Debian package build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev devscripts debhelper dh-python python3-all

      - name: Make postinst executable
        run: |
          ls -l DEBIAN
          chmod +x DEBIAN/postinst
          ls -l DEBIAN

      - name: Build Debian package
        run: |
          mkdir -p build/pyserv
          cp -R DEBIAN build/pyserv/
          mkdir -p build/pyserv/usr/bin
          cp usr/bin/pyserv build/pyserv/usr/bin/
          chmod +x build/pyserv/usr/bin/pyserv
          cd build
          dpkg-deb --build pyserv

      - name: Rename package with version
        run: |
          cd build
          mv pyserv.deb pyserv-v${{ env.PYSERV_VERSION }}.deb

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.PYSERV_VERSION }}
          name: Release v${{ env.PYSERV_VERSION }}
          files: build/pyserv-v${{ env.PYSERV_VERSION }}.deb
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
